wandb_version: 1

_n_gpu:
  desc: null
  value: 2
_name_or_path:
  desc: null
  value: ai4bharat/indic-bert
_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: huggingface
    huggingface_version: 4.20.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: gradients/albert\.embeddings\.word_embeddings\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.word_embeddings\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.word_embeddings\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.token_type_embeddings\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.token_type_embeddings\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.token_type_embeddings\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.embedding_hidden_mapping_in\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.embedding_hidden_mapping_in\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.embedding_hidden_mapping_in\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.value\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.value\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.value\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/classifier\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/classifier\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/classifier\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/classifier\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/classifier\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/classifier\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.pooler\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.pooler\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.pooler\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.pooler\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.pooler\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.pooler\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn_output\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn_output\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn_output\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn_output\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn_output\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn_output\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.ffn\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.LayerNorm\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.LayerNorm\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.LayerNorm\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.LayerNorm\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.LayerNorm\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.LayerNorm\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.dense\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.dense\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.dense\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.value\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.value\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.value\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.dense\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.dense\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.dense\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.key\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.key\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.key\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.key\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.key\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.key\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.query\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.query\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.query\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.query\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.query\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.attention\.query\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.full_layer_layer_norm\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.full_layer_layer_norm\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.full_layer_layer_norm\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.embedding_hidden_mapping_in\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.embedding_hidden_mapping_in\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.embedding_hidden_mapping_in\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.full_layer_layer_norm\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.full_layer_layer_norm\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.encoder\.albert_layer_groups\.0\.albert_layers\.0\.full_layer_layer_norm\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.LayerNorm\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.LayerNorm\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.LayerNorm\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.position_embeddings\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.position_embeddings\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.position_embeddings\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.LayerNorm\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.LayerNorm\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/albert\.embeddings\.LayerNorm\.weight.bins
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
    - 1: eval/loss
      5: 1
      6:
      - 1
    - 1: eval/accuracy
      5: 1
      6:
      - 1
    - 1: eval/precision
      5: 1
      6:
      - 1
    - 1: eval/recall
      5: 1
      6:
      - 1
    - 1: eval/f1
      5: 1
      6:
      - 1
    - 1: eval/runtime
      5: 1
      6:
      - 1
    - 1: eval/samples_per_second
      5: 1
      6:
      - 1
    - 1: eval/steps_per_second
      5: 1
      6:
      - 1
    - 1: train/train_runtime
      5: 1
      6:
      - 1
    - 1: train/train_samples_per_second
      5: 1
      6:
      - 1
    - 1: train/train_steps_per_second
      5: 1
      6:
      - 1
    - 1: train/total_flos
      5: 1
      6:
      - 1
    - 1: train/train_loss
      5: 1
      6:
      - 1
    python_version: 3.8.13
    start_time: 1664327620.679453
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 2
      - 7
      - 13
      - 23
      4: 3.8.13
      5: 0.13.2
      6: 4.20.1
      8:
      - 1
      - 5
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value: null
attention_probs_dropout_prob:
  desc: null
  value: 0
auto_find_batch_size:
  desc: null
  value: false
bad_words_ids:
  desc: null
  value: null
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
bos_token_id:
  desc: null
  value: 2
chunk_size_feed_forward:
  desc: null
  value: 0
classifier_dropout_prob:
  desc: null
  value: 0.1
cross_attention_hidden_size:
  desc: null
  value: null
data_seed:
  desc: null
  value: 4
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_bucket_cap_mb:
  desc: null
  value: None
ddp_find_unused_parameters:
  desc: null
  value: None
debug:
  desc: null
  value: '[]'
decoder_start_token_id:
  desc: null
  value: null
deepspeed:
  desc: null
  value: None
disable_tqdm:
  desc: null
  value: false
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: false
down_scale_factor:
  desc: null
  value: 1
early_stopping:
  desc: null
  value: false
embedding_size:
  desc: null
  value: 128
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: 3
eval_accumulation_steps:
  desc: null
  value: None
eval_batch_size:
  desc: null
  value: 16
eval_delay:
  desc: null
  value: 0
eval_steps:
  desc: null
  value: 497
evaluation_strategy:
  desc: null
  value: steps
exponential_decay_length_penalty:
  desc: null
  value: null
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
fsdp:
  desc: null
  value: '[]'
fsdp_min_num_params:
  desc: null
  value: 0
full_determinism:
  desc: null
  value: false
gap_size:
  desc: null
  value: 0
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
greater_is_better:
  desc: null
  value: true
group_by_length:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
hidden_act:
  desc: null
  value: gelu
hidden_dropout_prob:
  desc: null
  value: 0
hidden_size:
  desc: null
  value: 768
hub_model_id:
  desc: null
  value: None
hub_private_repo:
  desc: null
  value: false
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
    '2': LABEL_2
ignore_data_skip:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
initializer_range:
  desc: null
  value: 0.02
inner_group_num:
  desc: null
  value: 1
intermediate_size:
  desc: null
  value: 3072
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: false
jit_mode_eval:
  desc: null
  value: false
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
    LABEL_2: 2
label_names:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
layer_norm_eps:
  desc: null
  value: 1.0e-12
learning_rate:
  desc: null
  value: 1.0e-06
length_column_name:
  desc: null
  value: length
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: true
local_rank:
  desc: null
  value: -1
log_level:
  desc: null
  value: 20
log_level_replica:
  desc: null
  value: -1
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ai4bharat/indic-bert-finetuned-code-mixed-DS/runs/Sep28_02-13-30_AI-NLP01
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 497
logging_strategy:
  desc: null
  value: steps
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_position_embeddings:
  desc: null
  value: 512
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: eval_f1
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: albert
mp_parameters:
  desc: null
  value: ''
net_structure_type:
  desc: null
  value: 0
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_attention_heads:
  desc: null
  value: 12
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_hidden_groups:
  desc: null
  value: 1
num_hidden_layers:
  desc: null
  value: 12
num_memory_blocks:
  desc: null
  value: 0
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 20
optim:
  desc: null
  value: adamw_hf
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: ai4bharat/indic-bert-finetuned-code-mixed-DS
output_hidden_states:
  desc: null
  value: false
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: false
pad_token_id:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 8
per_device_train_batch_size:
  desc: null
  value: 8
per_gpu_eval_batch_size:
  desc: null
  value: None
per_gpu_train_batch_size:
  desc: null
  value: None
position_embedding_type:
  desc: null
  value: absolute
prediction_loss_only:
  desc: null
  value: false
prefix:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
push_to_hub:
  desc: null
  value: true
push_to_hub_model_id:
  desc: null
  value: None
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
ray_scope:
  desc: null
  value: last
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value: '[''wandb'']'
resume_from_checkpoint:
  desc: null
  value: None
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
run_name:
  desc: null
  value: albert-code-mixed-DS
save_on_each_node:
  desc: null
  value: false
save_steps:
  desc: null
  value: 497
save_strategy:
  desc: null
  value: steps
save_total_limit:
  desc: null
  value: None
seed:
  desc: null
  value: 43
sep_token_id:
  desc: null
  value: null
sharded_ddp:
  desc: null
  value: '[]'
skip_memory_metrics:
  desc: null
  value: true
task_specific_params:
  desc: null
  value: null
temperature:
  desc: null
  value: 1.0
tf32:
  desc: null
  value: None
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: true
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torch_dtype:
  desc: null
  value: null
torchdynamo:
  desc: null
  value: None
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 16
transformers_version:
  desc: null
  value: 4.20.1
type_vocab_size:
  desc: null
  value: 2
typical_p:
  desc: null
  value: 1.0
use_bfloat16:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
use_legacy_prediction_loop:
  desc: null
  value: false
vocab_size:
  desc: null
  value: 200000
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.01
xpu_backend:
  desc: null
  value: None
